import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ReactQueryProvider } from "@/app/ReactQueryProvider";
import Link from "next/link";
import { Home, PiggyBank, Tag } from "lucide-react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-stone-50 flex flex-col antialiased relative`}
      >
        <div className="absolute flex flex-col">
          <Link href="/dashboard">
            <button className="p-2 border hover:bg-gray-200" aria-label="Home">
              <Home />
            </button>
          </Link>
          <Link href="/dashboard/savings">
            <button
              className="p-2 border hover:bg-gray-200"
              aria-label="Savings"
            >
              <PiggyBank />
            </button>
          </Link>
          <Link href="/dashboard/tags">
            <button className="p-2 border hover:bg-gray-200" aria-label="Tags">
              <Tag />
            </button>
          </Link>
        </div>
        <ReactQueryProvider>{children}</ReactQueryProvider>
      </body>
    </html>
  );
}
