import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ReactQueryProvider } from "@/app/ReactQueryProvider";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Link href="/dashboard">
          <button className="p-2 border hover:bg-gray-200">Dashboard</button>
        </Link>
        <Link href="/dashboard/savings">
          <button className="p-2 border hover:bg-gray-200">Savings</button>
        </Link>
        <ReactQueryProvider>{children}</ReactQueryProvider>
      </body>
    </html>
  );
}
